### ISSUE TITLE
openssh-server hang

### ISSUE THREAD

**Issue by metsuke0** [NJonesUK/kali-packer-vagrant#1]
I get most of the way through the whole process, but during the apt update, a dialog is presented and input cannot be read.

>     virtualbox-iso: debconf: unable to initialize frontend: Dialog
>     virtualbox-iso: debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
>     virtualbox-iso: debconf: falling back to frontend: Readline
>     virtualbox-iso: Setting up python-wcwidth (0.1.7+dfsg1-2) ...
>     virtualbox-iso: Setting up theharvester (2.7.2~20180322-0kali1) ...
>     virtualbox-iso: Setting up openssh-server (1:7.7p1-2) ...
>     virtualbox-iso: debconf: unable to initialize frontend: Dialog
>     virtualbox-iso: debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
>     virtualbox-iso: debconf: falling back to frontend: Readline
>     virtualbox-iso: Configuring openssh-server
>     virtualbox-iso: --------------------------
>     virtualbox-iso:
>     virtualbox-iso: A new version (/tmp/fileag1eXh) of configuration file /etc/ssh/sshd_config is
>     virtualbox-iso: available, but the version installed currently has been locally modified.
>     virtualbox-iso:
>     virtualbox-iso:   1. install the package maintainer's version
>     virtualbox-iso:   2. keep the local version currently installed
>     virtualbox-iso:   3. show the differences between the versions
>     virtualbox-iso:   4. show a side-by-side difference between the versions
>     virtualbox-iso:   5. show a 3-way difference between available versions
>     virtualbox-iso:   6. do a 3-way merge between available versions
>     virtualbox-iso:   7. start a new shell to examine the situation
>     virtualbox-iso:

**Comment by NJonesUK** [comment]
Hey, thanks for the interest! I should have made it clear in the readme that this is still in development. This is the result of some changes made to the default SSHd configuration by something that I've yet to narrow down (as the changes happen before any changes I'm intending to make to that file). I've tried a number of ways to pass in the value, which is what you can see in the two lines shown below.

https://github.com/NJonesUK/kali-packer-vagrant/blob/dcc6c24cee955e549900d930b1d2408a4ccb918c/packer-scripts/virtualbox-guest-additions.sh#L2-L3

As a temporary fix, you can comment out the provisioner that installs the virtualbox guest additions, but this will break Vagrant shared folder integrations and a number of other things until you get the guest additions installed inside the vagrant box. Otherwise, I'm open to suggestions/pull requests on how to fix it.

**Comment by metsuke0** [comment]
Thanks for the workarounds and nice work so far!  "DEBIAN_FRONTEND=noninteractive" worked just fine.  I'm looking to utilize the vmware version once it is available.

**Comment by NJonesUK** [comment]
Can you share exactly what you did? I've still not quite got that worked out - as you say, the script currently in the repository hangs.

**Comment by metsuke0** [comment]
Actually, I've yet to test with a complete apt-get update, but that will come soon.  I'll report my findings once that happens.

**Comment by NJonesUK** [comment]
Turns out the ` DEBIAN_FRONTEND=noninteractive` goes after `sudo` - that now seems to have resolved the issue for me, and everything is building fine. I'll mark this as closed for now - please re-open if the latest version still has issues.
